import type { ProductArtKind } from '../types';

/**
 * Product art paths.
 *
 * Phase 1 uses locally generated, on-brand SVG illustrations rather than
 * placeholder photography, so nothing on the site implies product imagery we
 * do not have. Swap `artSet()` for real image URLs when the Hostinger catalog
 * is connected — nothing else needs to change.
 *
 * Generated by `npm run gen:images` (scripts/generate-product-art.mjs).
 */
export const ART_VIEWS = ['front', 'angle', 'detail', 'panel', 'box'] as const;

export type ArtView = (typeof ART_VIEWS)[number];

/** Three colourways per kind keep same-category grids visually distinguishable. */
export type ArtVariant = 1 | 2 | 3;

export function artSet(kind: ProductArtKind, variant: ArtVariant): string[] {
  return ART_VIEWS.map((view) => `/art/${kind}-${variant}-${view}.svg`);
}

export function artThumb(kind: ProductArtKind, variant: ArtVariant): string {
  return `/art/${kind}-${variant}-front.svg`;
}
