import { createHmac, timingSafeEqual } from 'node:crypto';
import { cookies } from 'next/headers';
import { env } from '@/lib/env';
import { verifyPassword } from './password';

/**
 * Admin session for the local order console.
 *
 * The password is never stored — only a scrypt hash, generated by
 * `npm run admin:hash`. The session cookie is an HMAC of an expiry timestamp,
 * so it cannot be forged or extended without `ADMIN_SESSION_SECRET`.
 *
 * This is a local operations tool, not a customer account system. Real accounts
 * with OTP arrive in a later phase.
 */

const COOKIE = 'itarang_admin';
const SESSION_HOURS = 12;

function sign(value: string, secret: string): string {
  return createHmac('sha256', secret).update(value).digest('hex');
}

export function isAdminConfigured(): boolean {
  const config = env();
  return Boolean(config.ADMIN_PASSWORD_HASH && config.ADMIN_SESSION_SECRET);
}

export async function createAdminSession(): Promise<void> {
  const secret = env().ADMIN_SESSION_SECRET;
  if (!secret) throw new Error('ADMIN_SESSION_SECRET is not configured.');

  const expires = Date.now() + SESSION_HOURS * 60 * 60 * 1000;
  const token = `${expires}.${sign(String(expires), secret)}`;

  const store = await cookies();
  store.set(COOKIE, token, {
    httpOnly: true,
    sameSite: 'lax',
    path: '/',
    maxAge: SESSION_HOURS * 60 * 60,
    secure: process.env.NODE_ENV === 'production',
  });
}

export async function destroyAdminSession(): Promise<void> {
  const store = await cookies();
  store.delete(COOKIE);
}

export async function isAdminAuthenticated(): Promise<boolean> {
  const config = env();
  if (!config.ADMIN_SESSION_SECRET) return false;

  const store = await cookies();
  const token = store.get(COOKIE)?.value;
  if (!token) return false;

  const [expiresRaw, signature] = token.split('.');
  const expires = Number(expiresRaw);
  if (!Number.isFinite(expires) || expires < Date.now()) return false;

  const expected = sign(expiresRaw, config.ADMIN_SESSION_SECRET);
  if (expected.length !== (signature?.length ?? 0)) return false;

  return timingSafeEqual(Buffer.from(expected, 'hex'), Buffer.from(signature, 'hex'));
}

export function checkAdminPassword(password: string): boolean {
  const hash = env().ADMIN_PASSWORD_HASH;
  if (!hash) return false;
  return verifyPassword(password, hash);
}
